import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  
        <div className="w-full xl:w-8/10 h-screen mx-auto
                    flex flex-col justify-start items-start
                   ">
          <Nav />
          <main className="w-full flex-grow
                       overflow-y-auto py-10
                       flex flex-col justify-start items-center">
              {children}
          </main> 
          <Footer />
        </div>
      </body>
    </html>
  );
}
